// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJw1PMW3sGZze7xKOAEo4WKUpnEawy2pQ',
    appId: '1:242503516385:web:d856ad4a234cffb72437a0',
    messagingSenderId: '242503516385',
    projectId: 'detranapp-75e56',
    authDomain: 'detranapp-75e56.firebaseapp.com',
    storageBucket: 'detranapp-75e56.firebasestorage.app',
    measurementId: 'G-23YGTN7DGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB02ffH7laIWAd-c1s-b12QyAgSORSGuMI',
    appId: '1:242503516385:android:479ab6e3ea44205a2437a0',
    messagingSenderId: '242503516385',
    projectId: 'detranapp-75e56',
    storageBucket: 'detranapp-75e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0j9qkdJdRIWXLnYCsT55HRs6EAWHW9sQ',
    appId: '1:242503516385:ios:c2e8fb8ce57fff812437a0',
    messagingSenderId: '242503516385',
    projectId: 'detranapp-75e56',
    storageBucket: 'detranapp-75e56.firebasestorage.app',
    iosBundleId: 'com.detran.app',
  );
}
